from .capability_catalog import (
    MailCapabilityCatalog,
    MailCapabilityCatalogEntry,
    get_mail_capability_catalog,
    get_mail_capability_descriptor,
)
from .data_source import MailDataSource, MailDataSourceOptions
from .driver_manager import MailDriverManager
from .language_workspace_catalog import (
    MailLanguageWorkspaceCatalog,
    MailLanguageWorkspaceCatalogEntry,
    get_mail_language_workspace_by_language,
)
from .provider_activation_catalog import (
    MailProviderActivationCatalog,
    MailProviderActivationCatalogEntry,
    get_mail_provider_activation_by_provider_key,
)
from .provider_catalog import (
    DEFAULT_mail_PROVIDER_KEY,
    MailProviderCatalog,
    MailProviderCatalogEntry,
    get_mail_provider_by_provider_key,
)
from .provider_extension_catalog import (
    MailProviderExtensionCatalog,
    MailProviderExtensionCatalogEntry,
    get_mail_provider_extension_catalog,
    get_mail_provider_extension_descriptor,
    get_mail_provider_extensions,
    get_mail_provider_extensions_for_provider,
    has_mail_provider_extension,
)
from .provider_package_catalog import (
    MailProviderPackageCatalog,
    MailProviderPackageCatalogEntry,
    get_mail_provider_package_by_package_identity,
    get_mail_provider_package_by_provider_key,
)
from .provider_package_loader import (
    MailProviderModuleNamespace,
    MailProviderPackageImportFn,
    MailProviderPackageInstallRequest,
    MailProviderPackageLoadRequest,
    MailProviderPackageLoader,
    MailProviderPackageLoaderException,
    MailResolvedProviderPackageLoadTarget,
    create_mail_provider_package_loader,
    install_mail_provider_package,
    install_mail_provider_packages,
    load_mail_provider_module,
    resolve_mail_provider_package_load_target,
)
from .provider_selection import (
    ParsedMailProviderUrl,
    mail_PROVIDER_SELECTION_PRECEDENCE,
    mail_PROVIDER_SELECTION_SOURCES,
    MailProviderSelection,
    MailProviderSelectionRequest,
    MailProviderSelectionSource,
    parse_mail_provider_url,
    resolve_mail_provider_selection,
)
from .provider_support import (
    mail_PROVIDER_SUPPORT_STATUSES,
    MailProviderSupport,
    MailProviderSupportStateRequest,
    MailProviderSupportStatus,
    create_mail_provider_support_state,
    resolve_mail_provider_support_status,
)
from .standard_contract import (
    MailClient,
    MailProviderDriver,
    MailRuntimeController,
    MailStandardContract,
)

__all__ = [
    "DEFAULT_mail_PROVIDER_KEY",
    "ParsedMailProviderUrl",
    "mail_PROVIDER_SELECTION_PRECEDENCE",
    "mail_PROVIDER_SELECTION_SOURCES",
    "mail_PROVIDER_SUPPORT_STATUSES",
    "MailCapabilityCatalog",
    "MailCapabilityCatalogEntry",
    "MailClient",
    "MailDataSource",
    "MailDataSourceOptions",
    "MailDriverManager",
    "MailLanguageWorkspaceCatalog",
    "MailLanguageWorkspaceCatalogEntry",
    "MailProviderActivationCatalog",
    "MailProviderActivationCatalogEntry",
    "MailProviderCatalog",
    "MailProviderCatalogEntry",
    "MailProviderDriver",
    "MailProviderExtensionCatalog",
    "MailProviderExtensionCatalogEntry",
    "MailProviderPackageCatalog",
    "MailProviderPackageCatalogEntry",
    "MailProviderPackageImportFn",
    "MailProviderPackageInstallRequest",
    "MailProviderPackageLoadRequest",
    "MailProviderPackageLoader",
    "MailProviderPackageLoaderException",
    "MailProviderModuleNamespace",
    "MailProviderSelection",
    "MailProviderSelectionRequest",
    "MailProviderSelectionSource",
    "MailProviderSupport",
    "MailProviderSupportStateRequest",
    "MailProviderSupportStatus",
    "MailResolvedProviderPackageLoadTarget",
    "MailRuntimeController",
    "MailStandardContract",
    "create_mail_provider_package_loader",
    "create_mail_provider_support_state",
    "get_mail_capability_catalog",
    "get_mail_capability_descriptor",
    "get_mail_language_workspace_by_language",
    "get_mail_provider_activation_by_provider_key",
    "get_mail_provider_by_provider_key",
    "get_mail_provider_extension_catalog",
    "get_mail_provider_extension_descriptor",
    "get_mail_provider_extensions",
    "get_mail_provider_extensions_for_provider",
    "get_mail_provider_package_by_package_identity",
    "get_mail_provider_package_by_provider_key",
    "has_mail_provider_extension",
    "install_mail_provider_package",
    "install_mail_provider_packages",
    "load_mail_provider_module",
    "parse_mail_provider_url",
    "resolve_mail_provider_package_load_target",
    "resolve_mail_provider_selection",
    "resolve_mail_provider_support_status",
]
