import { freezeMailRuntimeValue } from './runtime-freeze.js';
import type { MailLanguageWorkspaceCatalogEntry } from './types.js';

export const OFFICIAL_mail_LANGUAGE_WORKSPACE_KEYS = freezeMailRuntimeValue(['typescript', 'flutter', 'rust', 'java', 'csharp', 'swift', 'kotlin', 'go', 'python'] as const);

export const TYPESCRIPT_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'typescript',
  workspace: 'sdkwork-mail-sdk-typescript',
  workspaceCatalogRelativePath: 'src/language-workspace-catalog.ts',
  displayName: 'TypeScript',
  publicPackage: '@sdkwork/Mail-sdk',
  maturityTier: 'reference',
  controlSdk: true,
  runtimeBridge: true,
  currentRole: 'Executable reference implementation',
  workspaceSummary: 'This workspace is the executable reference implementation for provider-neutral Mail contracts, JDBC-style driver selection, standardized runtime lifecycle delegation, and provider package boundaries in sdkwork-mail-sdk.',
  roleHighlights: freezeMailRuntimeValue(['provider-neutral Mail contracts', 'JDBC-style driver and data-source model', 'assembly-driven provider catalog at src/provider-catalog.ts', 'assembly-driven capability catalog at src/capability-catalog.ts with required-baseline and optional-advanced surface descriptors', 'assembly-driven provider extension catalog at src/provider-extension-catalog.ts with unwrap-only extension metadata', 'surface-aware capability negotiation and degradation helpers with supported, degraded, and unsupported outcomes', 'assembly-driven runtimeSurfaceStandard methodTerms connectTransport, authenticateTransport, disconnectTransport, sendMail, probeMailbox, syncMailbox, healthCheck', 'assembly-driven runtimeSurfaceStandard failureCode native_sdk_not_available when no runtime bridge is registered', 'root public runtime surface constants mail_RUNTIME_SURFACE_METHODS and mail_RUNTIME_SURFACE_FAILURE_CODE', 'assembly-driven default provider constants DEFAULT_mail_PROVIDER_KEY, DEFAULT_mail_PROVIDER_PLUGIN_ID, and DEFAULT_mail_PROVIDER_DRIVER_ID', 'official provider packages for smtp and imap', 'TypeScript provider package statuses standardize every executable provider as a package_reference_boundary', 'TypeScript runtime bridge baseline loads provider packages through the provider-package loader SPI'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: freezeMailRuntimeValue({
    vendorSdkPackage: '@sdkwork/Mail-sdk-provider-smtp',
    vendorSdkImportPath: '@sdkwork/Mail-sdk-provider-smtp',
    recommendedEntrypoint: 'installMailProviderPackage',
    smokeCommand: 'npm run smoke',
    smokeMode: 'runtime-backed',
    smokeVariants: freezeMailRuntimeValue(['default'] as const),
  }),
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'src/provider-catalog.ts',
    capabilityCatalogRelativePath: 'src/capability-catalog.ts',
    providerExtensionCatalogRelativePath: 'src/provider-extension-catalog.ts',
    providerPackageCatalogRelativePath: 'src/provider-package-catalog.ts',
    providerActivationCatalogRelativePath: 'src/provider-activation-catalog.ts',
    providerSelectionRelativePath: 'src/provider-selection.ts',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'src/driver-manager.ts',
    dataSourceRelativePath: 'src/data-source.ts',
    providerSupportRelativePath: 'src/provider-support.ts',
    providerPackageLoaderRelativePath: 'src/provider-package-loader.ts',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'catalog-governed-mixed',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageScaffold: undefined,
});

export const FLUTTER_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'flutter',
  workspace: 'sdkwork-mail-sdk-flutter',
  workspaceCatalogRelativePath: 'lib/src/mail_language_workspace_catalog.dart',
  displayName: 'Flutter',
  publicPackage: 'mail_sdk',
  maturityTier: 'reference',
  controlSdk: true,
  runtimeBridge: true,
  currentRole: 'Executable mobile runtime baseline',
  workspaceSummary: 'This workspace is the executable Flutter/mobile runtime baseline for provider-neutral Mail contracts, SMTP default transport binding, and JDBC-style driver selection in sdkwork-mail-sdk.',
  roleHighlights: freezeMailRuntimeValue(['provider-neutral Mail contracts', 'JDBC-style driver manager and data source model for Flutter/mobile', 'official SMTP Flutter runtime binding through the mail_sdk_provider_SMTP plugin package', 'assembly-driven provider catalog, capability catalog, provider extension catalog, and provider selection helpers', 'default mobile provider remains SMTP unless the caller explicitly overrides selection', 'mobile runtime bridge remains mail transport focused and leaves realtime signaling to IM'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: freezeMailRuntimeValue({
    vendorSdkPackage: 'mail_sdk_provider_smtp',
    vendorSdkImportPath: 'package:mail_sdk_provider_smtp/mail_sdk_provider_smtp.dart',
    recommendedEntrypoint: 'MailDataSource',
    smokeCommand: 'flutter analyze',
    smokeMode: 'analysis-backed',
    smokeVariants: freezeMailRuntimeValue(['default'] as const),
  }),
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'lib/src/mail_provider_catalog.dart',
    capabilityCatalogRelativePath: 'lib/src/mail_capability_catalog.dart',
    providerExtensionCatalogRelativePath: 'lib/src/mail_provider_extension_catalog.dart',
    providerPackageCatalogRelativePath: 'lib/src/mail_provider_package_catalog.dart',
    providerActivationCatalogRelativePath: 'lib/src/mail_provider_activation_catalog.dart',
    providerSelectionRelativePath: 'lib/src/mail_provider_selection.dart',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'lib/src/mail_driver_manager.dart',
    dataSourceRelativePath: 'lib/src/mail_data_source.dart',
    providerSupportRelativePath: 'lib/src/mail_provider_support.dart',
    providerPackageLoaderRelativePath: 'lib/src/mail_provider_package_loader.dart',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'providers/mail_sdk_provider_{providerKey}',
    packagePattern: 'mail_sdk_provider_{providerKey}',
    manifestFileName: 'pubspec.yaml',
    readmeFileName: 'README.md',
    sourceFilePattern: 'lib/src/mail_provider_{providerKey}_package_contract.dart',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerKey}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerKey}', '{providerPascal}'] as const),
    referenceProviderKey: 'smtp',
    referenceStatus: 'package_reference_boundary',
    referenceRuntimeBridgeStatus: 'reserved',
    referenceVendorSdkPackage: 'mail_sdk_provider_smtp',
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const RUST_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'rust',
  workspace: 'sdkwork-mail-sdk-rust',
  workspaceCatalogRelativePath: 'src/language_workspace_catalog.rs',
  displayName: 'Rust',
  publicPackage: 'mail_sdk',
  maturityTier: 'reserved',
  controlSdk: true,
  runtimeBridge: false,
  currentRole: 'Reserved workspace skeleton',
  workspaceSummary: 'This workspace is the reserved Rust standard boundary for provider metadata, selection, and future control-plane integration.',
  roleHighlights: freezeMailRuntimeValue(['provider metadata and driver selection standards', 'reserved Rust workspace boundary for control-plane expansion', 'no runtime bridge is claimed in the current landing', 'code-level MailStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing', 'metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing', 'resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: undefined,
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'src/provider_catalog.rs',
    capabilityCatalogRelativePath: 'src/capability_catalog.rs',
    providerExtensionCatalogRelativePath: 'src/provider_extension_catalog.rs',
    providerPackageCatalogRelativePath: 'src/provider_package_catalog.rs',
    providerActivationCatalogRelativePath: 'src/provider_activation_catalog.rs',
    providerSelectionRelativePath: 'src/provider_selection.rs',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'src/driver_manager.rs',
    dataSourceRelativePath: 'src/data_source.rs',
    providerSupportRelativePath: 'src/provider_support.rs',
    providerPackageLoaderRelativePath: 'src/provider_package_loader.rs',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'providers/Mail-sdk-provider-{providerKey}',
    packagePattern: 'Mail-sdk-provider-{providerKey}',
    manifestFileName: 'Cargo.toml',
    readmeFileName: 'README.md',
    sourceFilePattern: 'src/lib.rs',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerKey}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerPascal}'] as const),
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const JAVA_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'java',
  workspace: 'sdkwork-mail-sdk-java',
  workspaceCatalogRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailLanguageWorkspaceCatalog.java',
  displayName: 'Java',
  publicPackage: 'com.sdkwork:Mail-sdk',
  maturityTier: 'reserved',
  controlSdk: true,
  runtimeBridge: false,
  currentRole: 'Reserved workspace skeleton',
  workspaceSummary: 'This workspace is the reserved Java standard boundary for provider metadata, driver selection, and future enterprise runtime integration.',
  roleHighlights: freezeMailRuntimeValue(['provider metadata and driver selection standards', 'reserved Java language boundary for future enterprise runtime integration', 'no runtime bridge is claimed in the current landing', 'code-level MailStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing', 'metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing', 'resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: undefined,
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailProviderCatalog.java',
    capabilityCatalogRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailCapabilityCatalog.java',
    providerExtensionCatalogRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailProviderExtensionCatalog.java',
    providerPackageCatalogRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailProviderPackageCatalog.java',
    providerActivationCatalogRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailProviderActivationCatalog.java',
    providerSelectionRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailProviderSelection.java',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailDriverManager.java',
    dataSourceRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailDataSource.java',
    providerSupportRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailProviderSupport.java',
    providerPackageLoaderRelativePath: 'src/main/java/com/sdkwork/Mail/metadata/MailProviderPackageLoader.java',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'providers/Mail-sdk-provider-{providerKey}',
    packagePattern: 'com.sdkwork:Mail-sdk-provider-{providerKey}',
    manifestFileName: 'pom.xml',
    readmeFileName: 'README.md',
    sourceFilePattern: 'src/main/java/com/sdkwork/Mail/provider/{providerKey}/MailProvider{providerPascal}PackageContract.java',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerKey}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerKey}', '{providerPascal}'] as const),
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const CSHARP_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'csharp',
  workspace: 'sdkwork-mail-sdk-csharp',
  workspaceCatalogRelativePath: 'src/SDKWork.Mail.Sdk/MailLanguageWorkspaceCatalog.cs',
  displayName: 'C#',
  publicPackage: 'Sdkwork.Mail.Sdk',
  maturityTier: 'reserved',
  controlSdk: true,
  runtimeBridge: false,
  currentRole: 'Reserved workspace skeleton',
  workspaceSummary: 'This workspace is the reserved C# standard boundary for provider metadata, driver selection, and future desktop or server-side control integration.',
  roleHighlights: freezeMailRuntimeValue(['provider metadata and driver selection standards', 'reserved C# language boundary for desktop or server-side control integration', 'no runtime bridge is claimed in the current landing', 'code-level MailStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing', 'metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing', 'resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: undefined,
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'src/SDKWork.Mail.Sdk/MailProviderCatalog.cs',
    capabilityCatalogRelativePath: 'src/SDKWork.Mail.Sdk/MailCapabilityCatalog.cs',
    providerExtensionCatalogRelativePath: 'src/SDKWork.Mail.Sdk/MailProviderExtensionCatalog.cs',
    providerPackageCatalogRelativePath: 'src/SDKWork.Mail.Sdk/MailProviderPackageCatalog.cs',
    providerActivationCatalogRelativePath: 'src/SDKWork.Mail.Sdk/MailProviderActivationCatalog.cs',
    providerSelectionRelativePath: 'src/SDKWork.Mail.Sdk/MailProviderSelection.cs',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'src/SDKWork.Mail.Sdk/MailDriverManager.cs',
    dataSourceRelativePath: 'src/SDKWork.Mail.Sdk/MailDataSource.cs',
    providerSupportRelativePath: 'src/SDKWork.Mail.Sdk/MailProviderSupport.cs',
    providerPackageLoaderRelativePath: 'src/SDKWork.Mail.Sdk/MailProviderPackageLoader.cs',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'providers/Sdkwork.Mail.Sdk.Provider.{providerPascal}',
    packagePattern: 'Sdkwork.Mail.Sdk.Provider.{providerPascal}',
    manifestFileName: 'Sdkwork.Mail.Sdk.Provider.{providerPascal}.csproj',
    readmeFileName: 'README.md',
    sourceFilePattern: 'src/MailProvider{providerPascal}PackageContract.cs',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerPascal}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerPascal}'] as const),
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const SWIFT_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'swift',
  workspace: 'sdkwork-mail-sdk-swift',
  workspaceCatalogRelativePath: 'Sources/MailSdk/MailLanguageWorkspaceCatalog.swift',
  displayName: 'Swift',
  publicPackage: 'MailSdk',
  maturityTier: 'reserved',
  controlSdk: true,
  runtimeBridge: false,
  currentRole: 'Reserved workspace skeleton',
  workspaceSummary: 'This workspace is the reserved Swift standard boundary for provider metadata, driver selection, and future iOS or macOS runtime bridge integration.',
  roleHighlights: freezeMailRuntimeValue(['provider metadata and driver selection standards', 'reserved Swift language boundary for iOS or macOS runtime bridge integration', 'no runtime bridge is claimed in the current landing', 'code-level MailStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing', 'metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing', 'resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: undefined,
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'Sources/MailSdk/MailProviderCatalog.swift',
    capabilityCatalogRelativePath: 'Sources/MailSdk/MailCapabilityCatalog.swift',
    providerExtensionCatalogRelativePath: 'Sources/MailSdk/MailProviderExtensionCatalog.swift',
    providerPackageCatalogRelativePath: 'Sources/MailSdk/MailProviderPackageCatalog.swift',
    providerActivationCatalogRelativePath: 'Sources/MailSdk/MailProviderActivationCatalog.swift',
    providerSelectionRelativePath: 'Sources/MailSdk/MailProviderSelection.swift',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'Sources/MailSdk/MailDriverManager.swift',
    dataSourceRelativePath: 'Sources/MailSdk/MailDataSource.swift',
    providerSupportRelativePath: 'Sources/MailSdk/MailProviderSupport.swift',
    providerPackageLoaderRelativePath: 'Sources/MailSdk/MailProviderPackageLoader.swift',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'Providers/MailSdkProvider{providerPascal}',
    packagePattern: 'MailSdkProvider{providerPascal}',
    manifestFileName: 'Package.swift',
    readmeFileName: 'README.md',
    sourceFilePattern: 'Sources/MailSdkProvider{providerPascal}/MailProvider{providerPascal}PackageContract.swift',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerPascal}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerPascal}'] as const),
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const KOTLIN_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'kotlin',
  workspace: 'sdkwork-mail-sdk-kotlin',
  workspaceCatalogRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailLanguageWorkspaceCatalog.kt',
  displayName: 'Kotlin',
  publicPackage: 'com.sdkwork:Mail-sdk',
  maturityTier: 'reserved',
  controlSdk: true,
  runtimeBridge: false,
  currentRole: 'Reserved workspace skeleton',
  workspaceSummary: 'This workspace is the reserved Kotlin standard boundary for provider metadata, driver selection, and future Android runtime bridge integration.',
  roleHighlights: freezeMailRuntimeValue(['provider metadata and driver selection standards', 'reserved Kotlin language boundary for Android runtime bridge integration', 'no runtime bridge is claimed in the current landing', 'code-level MailStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing', 'metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing', 'resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: undefined,
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailProviderCatalog.kt',
    capabilityCatalogRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailCapabilityCatalog.kt',
    providerExtensionCatalogRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailProviderExtensionCatalog.kt',
    providerPackageCatalogRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailProviderPackageCatalog.kt',
    providerActivationCatalogRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailProviderActivationCatalog.kt',
    providerSelectionRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailProviderSelection.kt',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailDriverManager.kt',
    dataSourceRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailDataSource.kt',
    providerSupportRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailProviderSupport.kt',
    providerPackageLoaderRelativePath: 'src/main/kotlin/com/sdkwork/Mail/metadata/MailProviderPackageLoader.kt',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'providers/Mail-sdk-provider-{providerKey}',
    packagePattern: 'com.sdkwork:Mail-sdk-provider-{providerKey}',
    manifestFileName: 'build.gradle.kts',
    readmeFileName: 'README.md',
    sourceFilePattern: 'src/main/kotlin/com/sdkwork/Mail/provider/{providerKey}/MailProvider{providerPascal}PackageContract.kt',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerKey}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerKey}', '{providerPascal}'] as const),
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const GO_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'go',
  workspace: 'sdkwork-mail-sdk-go',
  workspaceCatalogRelativePath: 'Mailstandard/language_workspace_catalog.go',
  displayName: 'Go',
  publicPackage: 'github.com/sdkwork/Mail-sdk',
  maturityTier: 'reserved',
  controlSdk: true,
  runtimeBridge: false,
  currentRole: 'Reserved workspace skeleton',
  workspaceSummary: 'This workspace is the reserved Go standard boundary for provider metadata, driver selection, and future control-plane tooling integration.',
  roleHighlights: freezeMailRuntimeValue(['provider metadata and driver selection standards', 'reserved Go language boundary for control-plane tooling integration', 'no runtime bridge is claimed in the current landing', 'code-level MailStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing', 'metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing', 'resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: undefined,
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'Mailstandard/provider_catalog.go',
    capabilityCatalogRelativePath: 'Mailstandard/capability_catalog.go',
    providerExtensionCatalogRelativePath: 'Mailstandard/provider_extension_catalog.go',
    providerPackageCatalogRelativePath: 'Mailstandard/provider_package_catalog.go',
    providerActivationCatalogRelativePath: 'Mailstandard/provider_activation_catalog.go',
    providerSelectionRelativePath: 'Mailstandard/provider_selection.go',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'Mailstandard/driver_manager.go',
    dataSourceRelativePath: 'Mailstandard/data_source.go',
    providerSupportRelativePath: 'Mailstandard/provider_support.go',
    providerPackageLoaderRelativePath: 'Mailstandard/provider_package_loader.go',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'providers/Mail-sdk-provider-{providerKey}',
    packagePattern: 'github.com/sdkwork/Mail-sdk-provider-{providerKey}',
    manifestFileName: 'go.mod',
    readmeFileName: 'README.md',
    sourceFilePattern: 'provider_package_contract.go',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerKey}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerPascal}'] as const),
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const PYTHON_mail_LANGUAGE_WORKSPACE_ENTRY: MailLanguageWorkspaceCatalogEntry = freezeMailRuntimeValue({
  language: 'python',
  workspace: 'sdkwork-mail-sdk-python',
  workspaceCatalogRelativePath: 'sdkwork_mail_sdk/language_workspace_catalog.py',
  displayName: 'Python',
  publicPackage: 'sdkwork-mail-sdk',
  maturityTier: 'reserved',
  controlSdk: true,
  runtimeBridge: false,
  currentRole: 'Reserved workspace skeleton',
  workspaceSummary: 'This workspace is the reserved Python standard boundary for provider metadata, driver selection, and future automation or control-plane integration.',
  roleHighlights: freezeMailRuntimeValue(['provider metadata and driver selection standards', 'reserved Python language boundary for automation or control-plane integration', 'no runtime bridge is claimed in the current landing', 'code-level MailStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing', 'metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing', 'resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing'] as const),
  defaultProviderContract: freezeMailRuntimeValue({
    providerKey: 'smtp',
    pluginId: 'Mail-smtp',
    driverId: 'sdkwork-mail-driver-smtp',
  }),
  providerSelectionContract: freezeMailRuntimeValue({
    sourceTerms: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    precedence: freezeMailRuntimeValue(['provider_url', 'provider_key', 'tenant_override', 'deployment_profile', 'default_provider'] as const),
    defaultSource: 'default_provider',
  }),
  providerSuppoMailontract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['builtin_registered', 'official_registered', 'official_unregistered', 'unknown'] as const),
  }),
  providerActivationContract: freezeMailRuntimeValue({
    statusTerms: freezeMailRuntimeValue(['package-boundary', 'control-metadata-only'] as const),
  }),
  runtimeBaseline: undefined,
  metadataScaffold: freezeMailRuntimeValue({
    providerCatalogRelativePath: 'sdkwork_mail_sdk/provider_catalog.py',
    capabilityCatalogRelativePath: 'sdkwork_mail_sdk/capability_catalog.py',
    providerExtensionCatalogRelativePath: 'sdkwork_mail_sdk/provider_extension_catalog.py',
    providerPackageCatalogRelativePath: 'sdkwork_mail_sdk/provider_package_catalog.py',
    providerActivationCatalogRelativePath: 'sdkwork_mail_sdk/provider_activation_catalog.py',
    providerSelectionRelativePath: 'sdkwork_mail_sdk/provider_selection.py',
  }),
  resolutionScaffold: freezeMailRuntimeValue({
    driverManagerRelativePath: 'sdkwork_mail_sdk/driver_manager.py',
    dataSourceRelativePath: 'sdkwork_mail_sdk/data_source.py',
    providerSupportRelativePath: 'sdkwork_mail_sdk/provider_support.py',
    providerPackageLoaderRelativePath: 'sdkwork_mail_sdk/provider_package_loader.py',
  }),
  providerPackageBoundaryContract: freezeMailRuntimeValue({
    modeTerms: freezeMailRuntimeValue(['catalog-governed-mixed', 'scaffold-per-provider-package'] as const),
    rootPublicPolicyTerms: freezeMailRuntimeValue(['none'] as const),
    lifecycleStatusTerms: freezeMailRuntimeValue(['package_reference_boundary', 'future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reference-baseline', 'reserved'] as const),
  }),
  providerPackageBoundary: freezeMailRuntimeValue({
    mode: 'scaffold-per-provider-package',
    rootPublicPolicy: 'none',
    lifecycleStatusTerms: freezeMailRuntimeValue(['future-runtime-bridge-only'] as const),
    runtimeBridgeStatusTerms: freezeMailRuntimeValue(['reserved'] as const),
  }),
  providerPackageScaffold: freezeMailRuntimeValue({
    relativePath: 'providers/provider-package-scaffold.md',
    directoryPattern: 'providers/sdkwork_mail_sdk_provider_{providerKey}',
    packagePattern: 'sdkwork-mail-sdk-provider-{providerKey}',
    manifestFileName: 'pyproject.toml',
    readmeFileName: 'README.md',
    sourceFilePattern: 'sdkwork_mail_sdk_provider_{providerKey}/__init__.py',
    sourceSymbolPattern: 'MailProvider{providerPascal}PackageContract',
    templateTokens: freezeMailRuntimeValue(['{providerKey}'] as const),
    sourceTemplateTokens: freezeMailRuntimeValue(['{providerKey}', '{providerPascal}'] as const),
    runtimeBridgeStatus: 'reserved',
    rootPublic: false,
    status: 'future-runtime-bridge-only',
  }),
});

export const mail_LANGUAGE_WORKSPACE_CATALOG: readonly MailLanguageWorkspaceCatalogEntry[] = freezeMailRuntimeValue([
  TYPESCRIPT_mail_LANGUAGE_WORKSPACE_ENTRY,
  FLUTTER_mail_LANGUAGE_WORKSPACE_ENTRY,
  RUST_mail_LANGUAGE_WORKSPACE_ENTRY,
  JAVA_mail_LANGUAGE_WORKSPACE_ENTRY,
  CSHARP_mail_LANGUAGE_WORKSPACE_ENTRY,
  SWIFT_mail_LANGUAGE_WORKSPACE_ENTRY,
  KOTLIN_mail_LANGUAGE_WORKSPACE_ENTRY,
  GO_mail_LANGUAGE_WORKSPACE_ENTRY,
  PYTHON_mail_LANGUAGE_WORKSPACE_ENTRY
]);

const mail_LANGUAGE_WORKSPACE_BY_KEY = new Map<string, MailLanguageWorkspaceCatalogEntry>(
  mail_LANGUAGE_WORKSPACE_CATALOG.map((entry) => [entry.language, entry]),
);

export function getMailLanguageWorkspaceCatalog(): readonly MailLanguageWorkspaceCatalogEntry[] {
  return mail_LANGUAGE_WORKSPACE_CATALOG;
}

export function getMailLanguageWorkspaceByLanguage(
  language: string,
): MailLanguageWorkspaceCatalogEntry | undefined {
  return mail_LANGUAGE_WORKSPACE_BY_KEY.get(language);
}

export function getMailLanguageWorkspace(
  language: string,
): MailLanguageWorkspaceCatalogEntry | undefined {
  return getMailLanguageWorkspaceByLanguage(language);
}
