import { freezeMailRuntimeValue } from './runtime-freeze.js';

export const mail_LOOKUP_HELPER_NAMING_PROFILE_TERMS = freezeMailRuntimeValue(['lower-camel-Mail', 'upper-camel-Mail', 'snake-case-Mail'] as const);

export const mail_LOOKUP_HELPER_NAMING_FAMILY_TERMS = freezeMailRuntimeValue(['provider-catalog-by-provider-key', 'provider-package-by-provider-key', 'provider-package-by-package-identity', 'provider-activation-by-provider-key', 'capability-catalog', 'capability-descriptor-by-capability-key', 'provider-extension-catalog', 'provider-extension-descriptor-by-extension-key', 'provider-extensions-for-provider', 'provider-extensions-by-extension-keys', 'provider-extension-membership', 'language-workspace-by-language', 'provider-url-parser', 'provider-selection-resolver', 'provider-support-status-resolver', 'provider-support-state-factory', 'provider-package-loader-factory', 'provider-package-load-target-resolver', 'provider-module-loader', 'single-provider-package-installer', 'batch-provider-package-installer'] as const);

export const mail_LOOKUP_HELPER_NAMING_STANDARD = freezeMailRuntimeValue({
  profileTerms: mail_LOOKUP_HELPER_NAMING_PROFILE_TERMS,
  familyTerms: mail_LOOKUP_HELPER_NAMING_FAMILY_TERMS,
  profiles: freezeMailRuntimeValue({
  "lower-camel-Mail": freezeMailRuntimeValue({
    languages: freezeMailRuntimeValue(['typescript', 'flutter', 'java', 'swift', 'kotlin'] as const),
    helpers: freezeMailRuntimeValue({
  "providerCatalogByProviderKey": 'getMailProviderByProviderKey',
  "providerPackageByProviderKey": 'getMailProviderPackageByProviderKey',
  "providerPackageByPackageIdentity": 'getMailProviderPackageByPackageIdentity',
  "providerActivationByProviderKey": 'getMailProviderActivationByProviderKey',
  "capabilityCatalog": 'getMailCapabilityCatalog',
  "capabilityDescriptorByCapabilityKey": 'getMailCapabilityDescriptor',
  "providerExtensionCatalog": 'getMailProviderExtensionCatalog',
  "providerExtensionDescriptorByExtensionKey": 'getMailProviderExtensionDescriptor',
  "providerExtensionsForProvider": 'getMailProviderExtensionsForProvider',
  "providerExtensionsByExtensionKeys": 'getMailProviderExtensions',
  "providerExtensionMembership": 'hasMailProviderExtension',
  "languageWorkspaceByLanguage": 'getMailLanguageWorkspaceByLanguage',
  "providerUrlParser": 'parseMailProviderUrl',
  "providerSelectionResolver": 'resolveMailProviderSelection',
  "providerSupportStatusResolver": 'resolveMailProviderSupportStatus',
  "providerSupportStateFactory": 'createMailProviderSupportState',
  "providerPackageLoaderFactory": 'createMailProviderPackageLoader',
  "providerPackageLoadTargetResolver": 'resolveMailProviderPackageLoadTarget',
  "providerModuleLoader": 'loadMailProviderModule',
  "singleProviderPackageInstaller": 'installMailProviderPackage',
  "batchProviderPackageInstaller": 'installMailProviderPackages',
} as const),
  } as const),
  "upper-camel-Mail": freezeMailRuntimeValue({
    languages: freezeMailRuntimeValue(['csharp', 'go'] as const),
    helpers: freezeMailRuntimeValue({
  "providerCatalogByProviderKey": 'GetMailProviderByProviderKey',
  "providerPackageByProviderKey": 'GetMailProviderPackageByProviderKey',
  "providerPackageByPackageIdentity": 'GetMailProviderPackageByPackageIdentity',
  "providerActivationByProviderKey": 'GetMailProviderActivationByProviderKey',
  "capabilityCatalog": 'GetMailCapabilityCatalog',
  "capabilityDescriptorByCapabilityKey": 'GetMailCapabilityDescriptor',
  "providerExtensionCatalog": 'GetMailProviderExtensionCatalog',
  "providerExtensionDescriptorByExtensionKey": 'GetMailProviderExtensionDescriptor',
  "providerExtensionsForProvider": 'GetMailProviderExtensionsForProvider',
  "providerExtensionsByExtensionKeys": 'GetMailProviderExtensions',
  "providerExtensionMembership": 'HasMailProviderExtension',
  "languageWorkspaceByLanguage": 'GetMailLanguageWorkspaceByLanguage',
  "providerUrlParser": 'ParseMailProviderUrl',
  "providerSelectionResolver": 'ResolveMailProviderSelection',
  "providerSupportStatusResolver": 'ResolveMailProviderSupportStatus',
  "providerSupportStateFactory": 'CreateMailProviderSupportState',
  "providerPackageLoaderFactory": 'CreateMailProviderPackageLoader',
  "providerPackageLoadTargetResolver": 'ResolveMailProviderPackageLoadTarget',
  "providerModuleLoader": 'LoadMailProviderModule',
  "singleProviderPackageInstaller": 'InstallMailProviderPackage',
  "batchProviderPackageInstaller": 'InstallMailProviderPackages',
} as const),
  } as const),
  "snake-case-Mail": freezeMailRuntimeValue({
    languages: freezeMailRuntimeValue(['rust', 'python'] as const),
    helpers: freezeMailRuntimeValue({
  "providerCatalogByProviderKey": 'get_mail_provider_by_provider_key',
  "providerPackageByProviderKey": 'get_mail_provider_package_by_provider_key',
  "providerPackageByPackageIdentity": 'get_mail_provider_package_by_package_identity',
  "providerActivationByProviderKey": 'get_mail_provider_activation_by_provider_key',
  "capabilityCatalog": 'get_mail_capability_catalog',
  "capabilityDescriptorByCapabilityKey": 'get_mail_capability_descriptor',
  "providerExtensionCatalog": 'get_mail_provider_extension_catalog',
  "providerExtensionDescriptorByExtensionKey": 'get_mail_provider_extension_descriptor',
  "providerExtensionsForProvider": 'get_mail_provider_extensions_for_provider',
  "providerExtensionsByExtensionKeys": 'get_mail_provider_extensions',
  "providerExtensionMembership": 'has_mail_provider_extension',
  "languageWorkspaceByLanguage": 'get_mail_language_workspace_by_language',
  "providerUrlParser": 'parse_mail_provider_url',
  "providerSelectionResolver": 'resolve_mail_provider_selection',
  "providerSupportStatusResolver": 'resolve_mail_provider_support_status',
  "providerSupportStateFactory": 'create_mail_provider_support_state',
  "providerPackageLoaderFactory": 'create_mail_provider_package_loader',
  "providerPackageLoadTargetResolver": 'resolve_mail_provider_package_load_target',
  "providerModuleLoader": 'load_mail_provider_module',
  "singleProviderPackageInstaller": 'install_mail_provider_package',
  "batchProviderPackageInstaller": 'install_mail_provider_packages',
} as const),
  } as const),
  } as const),
} as const);
